In [66]:
import numpy as np
a=np.array([[1,2,3,4],(3,4,8,6)])
print(a)

[[1 2 3 4]
 [3 4 8 6]]


In [67]:
a=np.array((1,2,3,4))
print(a)

[1 2 3 4]


In [68]:
a=np.array(((1,20,0),(2,4,8)))
print(a)

[[ 1 20  0]
 [ 2  4  8]]


In [124]:
import numpy.matlib
a=np.array([[1,2,3,4],[4,5,6,7]])
print("a is",a)
print("shape of a is",a.shape)
print(" ")

print("add 2 to a is",a+2)
print(" ")

print("min is row wise",a.max(axis=1))
print(" ")

print("min is column wise",a.max(axis=0))
print(" ")

b=np.array([[1,12,0,3],[2,4,8,0]])
print("multiplication of a and b is ",a*b)
print("sin of a is",np.sin(b))
print(" ")

print("b is",b)
print(" ")

print(b.shape)
print(" ")

print("sort row of b",np.sort(b,axis=1))
print(" ")

print("i_add_ is b ",b.__iadd__(3))
print(" ")
print("sum is",sum(a))
print(b.__lshift__(1)) 



a is [[1 2 3 4]
 [4 5 6 7]]
shape of a is (2, 4)
 
add 2 to a is [[3 4 5 6]
 [6 7 8 9]]
 
min is row wise [4 7]
 
min is column wise [4 5 6 7]
 
multiplication of a and b is  [[ 1 24  0 12]
 [ 8 20 48  0]]
sin of a is [[ 0.84147098 -0.53657292  0.          0.14112001]
 [ 0.90929743 -0.7568025   0.98935825  0.        ]]
 
b is [[ 1 12  0  3]
 [ 2  4  8  0]]
 
(2, 4)
 
sort row of b [[ 0  1  3 12]
 [ 0  2  4  8]]
 
i_add_ is b  [[ 4 15  3  6]
 [ 5  7 11  3]]
 
sum is [ 5  7  9 11]


In [4]:
import pandas as pd
df=pd.read_excel("NamesAndAges.xlsx")
df.head(10)

Names  Age
0  Andreas   21
1   George   22
2    Steve   20
3    Sarah   19
4   Joanna   18
5    Hanna   23

In [34]:
ser1=pd.Series(df['Names'],[2,3,4,5,6])
print(ser1)


2     Steve
3     Sarah
4    Joanna
5     Hanna
6       NaN
Name: Names, dtype: object


In [32]:
ser=pd.Series([12,34,5,6,8],[2,3,4,3,4])#index is last array
print(ser)
a=ser.max()
print(a)

2    12
3    34
4     5
3     6
4     8
dtype: int64
34


In [20]:
ser.loc[[2,4]]

2     Steve
4    Joanna
Name: Names, dtype: object

In [35]:
ser2=pd.Series([3,45,76,9,0,2,1])
print(ser2)

0     3
1    45
2    76
3     9
4     0
5     2
6     1
dtype: int64


In [36]:
a=ser1.eq(ser2,fill_value=0)
print(a)

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool


In [37]:
ser2.take(indices=[0,3])

0    3
3    9
dtype: int64

In [42]:
ser2.xs(key=4)

0

In [44]:
a=ser.ge(ser2,fill_value=0)
print(a)

0    False
1    False
2    False
3     True
3    False
4     True
4     True
5    False
6    False
dtype: bool


In [45]:
f=[2,3,4,5]
s=[4,5,6,7]
result=f.pow(s)
print(result)

AttributeError: 'list' object has no attribute 'pow'